export const db = null; export const auth = { currentUser: null, onIdTokenChanged: (...a: any[]) => () => {}, onAuthStateChanged: (...a: any[]) => () => {} }; export const storage = null;
export default null;
export const OperationType = { CANCEL: "cancel", RUN: "run", RETRY: "retry" };
export const collection = (...a: any[]) => ({});
export const onSnapshot = (...a: any[]) => () => {};
export const query = (...a: any[]) => ({});
export const where = (...a: any[]) => ({});
export const orderBy = (...a: any[]) => ({});
export const limit = (...a: any[]) => ({});
export const getDocs = async (...a: any[]) => ({ docs: [], empty: true, size: 0 });
export const getDoc  = async (...a: any[]) => ({ exists: () => false, data: () => null, id: "" });
export const addDoc  = async (...a: any[]) => ({ id: "" });
export const updateDoc  = async () => {};
export const deleteDoc  = async () => {};
export const setDoc     = async () => {};
export const doc        = (...a: any[]) => ({});
export const serverTimestamp = () => null;
export const Timestamp   = { now: () => new Date(), fromDate: (d: any) => d };
export const increment   = (n: number) => n;
export const arrayUnion  = (...a: any[]) => a;
export const arrayRemove = (...a: any[]) => [];
export const GeoPoint    = class { constructor(public lat=0, public lng=0){} };
export const onAuthStateChanged = (...a: any[]) => () => {};
export const signOut = async () => {};
export const signInWithPhoneNumber = async (...a: any[]) => ({ confirm: async () => ({}) });
export const RecaptchaVerifier = class { constructor(...a: any[]){} render(){return Promise.resolve(0);} clear(){} };
export const PhoneAuthProvider = class { static credential(...a: any[]){ return {}; } };
export const signInWithCredential = async (...a: any[]) => ({ user: null });
export const createUserWithEmailAndPassword = async (...a: any[]) => ({ user: null });
export const signInWithEmailAndPassword     = async (...a: any[]) => ({ user: null });
export const updateProfile  = async (...a: any[]) => {};
export const updateEmail    = async (...a: any[]) => {};
export const updatePassword = async (...a: any[]) => {};
export const sendPasswordResetEmail     = async (...a: any[]) => {};
export const sendEmailVerification      = async (...a: any[]) => {};
export const deleteUser     = async (...a: any[]) => {};
export const reauthenticateWithCredential = async (...a: any[]) => ({ user: null });
export const EmailAuthProvider = { credential: (...a: any[]) => ({}) };
export const GoogleAuthProvider = class { constructor(){} static credential(...a: any[]){ return {}; } };
export const signInWithPopup  = async (...a: any[]) => ({ user: null });
export const getIdToken       = async (...a: any[]) => "";
export const getAuth          = (...a: any[]) => null;
export const initializeApp    = (...a: any[]) => ({});
export const getFirestore     = (...a: any[]) => null;
export const getStorage       = (...a: any[]) => null;
export const googleProvider = { providerId: 'google.com' };
export const facebookProvider = { providerId: 'facebook.com' };
export const twitterProvider  = { providerId: 'twitter.com' };
export const githubProvider   = { providerId: 'github.com' };
export const appleProvider    = { providerId: 'apple.com' };
export const connectFirestoreEmulator = (...a: any[]) => {};
export const connectAuthEmulator      = (...a: any[]) => {};
export const getAnalytics = (...a: any[]) => null;
export const logEvent     = (...a: any[]) => {};
export const httpsCallable = (...a: any[]) => async (...b: any[]) => ({ data: null });
export const getFunctions  = (...a: any[]) => null;